### ISSUE TITLE
Could not find source plugin for kafka

### ISSUE THREAD

**Issue by AssafKatz3** [ansible/event-driven-ansible#102]
Hi,
I am trying to use [kafka-test](../blob/main/rulebooks/kafka-test-rules.yml) but get:

`
2023-03-14 13:41:17,276 - ansible_rulebook.engine - ERROR - Source error
Traceback (most recent call last):
  File "/home/azureuser/.local/lib/python3.10/site-packages/ansible_rulebook/engine.py", line 93, in start_source
    raise Exception(
Exception: Could not find source plugin for kafka
2023-03-14 13:41:17,276 - ansible_rulebook.engine - ERROR - Shutting down source: kafka error : Could not find source plugin for kafka
`

How should I install/configure it?

Thanks

**Comment by AssafKatz3** [comment]
Hi,
I managed to overcome it by using ansible.eda.kafka instead just kafka. But this problem is still existed.
Thanks

**Comment by bzwei** [comment]
The example is meant to be used as a local test. You should use `-S` option for ansible_rulebook CLI.
The recommended way to use the plugin is by `ansible.eda.kafka`. Make sure you have installed the ansible.eda collection correctly.

**Comment by Bigsmooth68** [comment]
I have a similar issue even with `ansible.eda.kafka` change.
I would suggest to update the example https://github.com/ansible/event-driven-ansible/blob/main/rulebooks/kafka-test-rules.yml.

**Comment by ssbarnea** [comment]
This is currently what I see as breaking the integration tests on CI, so we need to fix it ASAP to bring the CI status to green.
