### ISSUE TITLE
ntlm authentication for an event source

### ISSUE THREAD

**Issue by TheITRx** [ansible/event-driven-ansible#163]
I'm trying to write an event source plugin where I'm gathering data from a REST API endpoint. 

Your guides are to use asyncio an aiohttp for asynchronous  processing.

The API I need poll data from only supports NTLM authentication. Unfortunately, I have not found a way to make this work with aiohttp. 

Any idea what my options are if NTLM is the only supported auth for my API?

Thanks!

**Comment by Alex-Izquierdo** [comment]
Hello. I would try to implement my own auth logic, you can take [this as reference](https://github.com/requests/requests-ntlm). Or even build a more reusable library [for the ecosystem](https://docs.aiohttp.org/en/stable/third_party.html).

**Comment by TheITRx** [comment]
@Alex-Izquierdo I end up using httpx and httpx-ntlm for my requests. httpx  supports async. 

...Then I swing my data to the asyncio queue. 

https://github.com/encode/httpx
https://github.com/ulodciv/httpx-ntlm

Working solid so far.

**Comment by Alex-Izquierdo** [comment]
Glad to know.  I close the issue then.
