### ISSUE TITLE
Where do you install the collection and source event plugins?

### ISSUE THREAD

**Issue by aapdyna** [ansible/event-driven-ansible#170]
Hi Team, 

Do the event source plugins get installed on the EDA controller or the AAP controller?

Thanks

**Comment by Alex-Izquierdo** [comment]
Hello @aapdyna the collection that contains the source plugins must be installed in the Decision Environment, the container image that must have the collections alongside ansible-rulebook application. 

Feel free to ask in our [matrix chat](https://matrix.to/#/#eda:ansible.com)

**Comment by aapdyna** [comment]
Hi @Alex-Izquierdo, thanks so much for the prompt response! Much appreciated and your input is very helpful. 

Thanks on the matrix chat. Will ask there in the future too:)
