### ISSUE TITLE
Branch selection for Event Driven Ansible Controller Projects

### ISSUE THREAD

**Issue by felipe4334** [ansible/event-driven-ansible#214]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/ansible-rulebook/issues) for duplicates.
- [X] I understand that ansible-rulebook is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

Currently I could not find a way to specify the branch name when creating a project inside of EDA, by default it seems to use main/master branch. And when I try to use https://urlname.com/groupname/reponame/-/tree/branch_name I get a failure to login.

I'm using gitlab as my Git repo.

### Steps to reproduce

Go into projects and create a new project with a Git link. Then try and use code from a different branch other than main.

### Current results

extensions/eda/rulebooks location cant be found, (since I have not merge testing changes to main branch)

### Sugested feature result

There should be an option or a way of selecting branches, same as automation controller.

**Comment by Alex-Izquierdo** [comment]
Hello @felipe4334 This feature [is already implemented](https://github.com/ansible/eda-server/pull/777)
For commercial subscriptions of Ansible Automation Platform, please contact with your Red Hat Support.
