### ISSUE TITLE
Website: https://www.ansible.com/event-driven doesn't exist

### ISSUE THREAD

**Issue by konstruktoid** [ansible/event-driven-ansible#31]
https://www.ansible.com/event-driven is a 404

**Comment by it-pappa** [comment]
I guess it will be live later today maby? Hope it will. I am looking forward to test this!

**Comment by konstruktoid** [comment]
I got a Vagantfile to assist with the https://github.com/ansible/ansible-rulebook installation if you'd be interested @it-pappa. I'm planning on submitting it as a PR, with doc updates, later this evening to the rulebook project.

**Comment by konstruktoid** [comment]
Fixed, redirect to https://www.ansible.com/use-cases/event-driven-automation
