### ISSUE TITLE
Installation issue on Fedora 36 

### ISSUE THREAD

**Issue by lm-gunjan** [ansible/event-driven-ansible#33]
Fedora 36 is being recognised as redhat in main task of install_ansible_rulebook therefore it try to include task install_redhat.yml which doesn't exist.

{{ ansible_os_family }} returns redhat which should be fedora

https://github.com/ansible/event-driven-ansible/blob/445579834ceb418ba5f34befe3ef566ad7475458/roles/install_ansible_rulebook/tasks/main.yml

**ERROR**
`TASK [ansible.eda.install_ansible_rulebook : Install for RedHat] ********************************************************************************************************************
fatal: [localhost]: FAILED! => {"reason": "Could not find or access '/home/gunjankumar/.ansible/collections/ansible_collections/ansible/eda/playbooks/install_redhat.yml' on the Ansible Controller."}`

**Comment by konstruktoid** [comment]
> {{ ansible_os_family }} returns redhat which should be fedora

This is actually correct, Fedora is a distribution in the RedHat family.
Same as Ubuntu is a distribution in the Debian family.

The file should be renamed to `install_redhat.yml`.
