### ISSUE TITLE
Playbook install-rulebook-cli.yml is poorly named breaking legal ansible-playbook calling conventions

### ISSUE THREAD

**Issue by tonykay** [ansible/event-driven-ansible#39]
Whilst not a big issue, the use of dashes like in role names should be avoided (IMHO). The use of dashes in the playbook name breaks the ability to follow simple patterns like

```
ansible-galaxy collection install ansible.eda
ansible-playbook ansible.eda.install-rulebook-cli
```

The above fails. However, simply renaming to `install_rulebook_cli.yml` and it succeeds

**Comment by benthomasson** [comment]
Nice catch

**Comment by ttuffin** [comment]
Thanks for the report. We are in the process of refactoring the installer and will fix it there.
