### ISSUE TITLE
Document conditions for file_watch

### ISSUE THREAD

**Issue by rndmh3ro** [ansible/event-driven-ansible#50]
I'm trying to use the file_watch event source. However I have no idea on what conditions I can execute actions. The docs (https://github.com/ansible/event-driven-ansible/blob/main/plugins/event_source/file_watch.py) do not mention it and I couldn't find out from the source code.

What am I missing?

**Comment by Alex-Izquierdo** [comment]
Hello. You can find in [ansible-rulebooks docs](https://ansible-rulebook.readthedocs.io/en/latest/rules.html) how to write rules and conditions. It is still necessary to improve the plugin documentation to indicate which is the structure of the event it generates. In the source code you can see that for every file that is created, deleted or modified it creates an event with the fields:
```
change
src_path
type
root_path
```

As a simple example you could write a rule like: 
```
name:  Trigger on deleted
condition:  event.change == "deleted"
action:
  print_event:
```

**Comment by rndmh3ro** [comment]
Thanks, that's working.
