### ISSUE TITLE
run_job_template action issue

### ISSUE THREAD

**Issue by jonsaydam** [ansible/event-driven-ansible#83]
Hi,

Using run_job_template action in my rulebook. It triggers the job but then giving below error where it tries to get the result from the template. I think it is caused because of the double quotes after the job ID. Is anyone else having the same issue?

ansible_rulebook.exception.ControllerApiException: Failed to get from https://<controller_url>/api/v2/jobs/jobID//job_events/. Status: 404, Body: {"detail":"The requested resource could not be found."}

Thanks

Jon

**Comment by Alex-Izquierdo** [comment]
@bzwei

**Comment by Alex-Izquierdo** [comment]
Hi @jonsaydam, seems that this is an issue for https://github.com/ansible/ansible-rulebook
We would need the output of `ansible-rulebook --version` as well as the rulebook and any other relevant data that allows us to reproduce the error.

**Comment by bzwei** [comment]
@jonsaydam I believe the issue has been fixed. Try to use the latest ansible-rulebook.

**Comment by jonsaydam** [comment]
The issue is resolved in the new version. Thanks
