### ISSUE TITLE
Authentication possibilities

### ISSUE THREAD

**Issue by KieniL** [ansible/event-driven-ansible#87]
Dear EDA-Team,

I found out about this repository and I am currently checking if it would be an alternative for ansible-pull which I am not getting to find nice fits.
Would I find appealing in EDA is the possibility to trigger automation initiatited from client so that a pull-based approach could be Designer.

Are there any plans on your side for implementing  authentication or Authorization since as far as I found out the endpoint is anonymous?

Since there are already other requests from Kubernetes/GCP the IdP from there could maybe used?

Additionally, since the ansible-rulebook starts the listening process. Will there be possibilities for TLS or is there already a documentation about it?

Thank you.

Best Regards,
KieniL

**Comment by bzwei** [comment]
Are you talking about the webhook source plugin? Yes. We are adding the TLS and authentication support. I will update once the PR is created.
