### ISSUE TITLE
Does rulebook allow it to play a specific role based playbook?

### ISSUE THREAD

**Issue by darthVikes** [ansible/event-driven-ansible#97]
For ansible-playbooks I have an ansible.cfg file that allows me to change the roles directory, Does ansible-rulebook allow me to do the same?  Does the runner call ansible-playbook to where your playbook is?

ansible.cfg
-----
[defaults]
# additional paths to search for roles in, colon separated
roles_path    = ./roles
-----

ansible-rulebook -r rulebook.yaml -i inventory.yml --verbose

rulebook.yaml
---
- name: Read messages from a kafka topic and act on them
  hosts: all
  ## Define our source for events
  sources:
    - ansible.eda.kafka:
        host: localhost
        port: 9092
        topic: eda-topic
        group_id:

  ## Define the conditions we are looking for
  rules:
    - name: Say Hello
      condition: event.message == "Ansible is cool"
      ## Define the action we should take should the condition be met
      action:
        run_playbook:
          name: expand-vm-disks.yaml

expand-vm-disks.yaml
---
- hosts: localhost
  gather_facts: false
  vars:
      guest_os: "{{ lookup('env','guest_os') }}"
  roles:
    - expand-vm-disks

pwd
/ansible/rulebook.yaml
/ansible/inventory.yaml
/ansible/expand-vm-disks.yaml
/ansible/ansible.cfg
/ansible/roles/expand-vm-disks/tasks/main.yaml

ERROR:

2023-03-09 21:05:05,789 - ansible_rulebook.builtin - INFO - Calling Ansible runner
ERROR! the role 'expand-vm-disks' was not found in /tmp/run_playbooky5u9tb11/project/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/tmp/run_playbooky5u9tb11/project

The error appears to be in '/tmp/run_playbooky5u9tb11/project/expand-vm-disks.yaml': line 39, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - expand-vm-disks
      ^ here

**Comment by Alex-Izquierdo** [comment]
Hi @darthVikes Thanks for your feedback. 
Ansible-rulebook uses ansible-runner to execute ansible-playbook within a custom and temporal directory where the playbook, the inventory or variables are passed. Currently there is no support for custom config files for ansible. You can create a feature request in [ansible-rulebook](https://github.com/ansible/ansible-rulebook) project. 

As a workaround I suggest use your custom config through the `ANSIBLE_CONFIG` environment variable or moving that config into the default expected paths, like `~/.ansible.cfg` you can see more details in the [ansible documentation.](https://docs.ansible.com/ansible/latest/reference_appendices/config.html)

**Comment by darthVikes** [comment]
Humm, ok tried adding ANSIBLE_CONFIG  and copying it to ~/.ansible.cfg, but same issue.

**Comment by darthVikes** [comment]
Gotcha! thanks! Apprecate the quick response.

**Comment by darthVikes** [comment]
Question was answered.
